# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Pipe

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'External-Attention-MindSpore/**'
      - '.github/workflows/**'
  push:
    branches: [ "main" ]
    paths:
      - 'External-Attention-MindSpore/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies and MindSpore
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Install MindSpore
    #  shell: bash
    #  env:
    #    OS: ubuntu-latest
    #    PYTHON: 3.7
    #  run: |
    #    python .github/install_mindspore.py
    #    pip install -r download.txt
    - name: Analysing the External-Attention-MindSpore code with pylint
      run: |
        pylint External-Attention-MindSpore --rcfile=.github/pylint.conf
    - name: Analysing the tests code with pylint
      run: |
        pylint tests --rcfile=.github/pylint.conf
